title: "Votre Nom"
description: "Portfolio, articles et créations"
url: "https://camchampblay.github.io"
baseurl: ""                     # user site => keep empty

remote_theme: patdryburgh/hitchens

plugins:
  - jekyll-remote-theme
  - jekyll-paginate

show_excerpts: true
excerpt_length: 24
paginate: 10
paginate_path: "/page/:num/"
